services:
  app:
    build: .
    container_name: foliomine-container
    command: python manage.py runserver 0.0.0.0:8000 && python manage.py tailwind start
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - .:/home/app