# Generated by Django 4.1.4 on 2023-06-12 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edu_end_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exp_start_date', models.DateField()),
                ('exp_end_date', models.DateField()),
                ('job_profile', models.TextField(max_length=50)),
                ('company_name', models.TextField(max_length=50)),
                ('details', models.TextField(max_length=2000)),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_start_date', models.DateField()),
                ('proj_end_date', models.DateField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_details', models.TextField(max_length=2000)),
                ('project_code_link', models.URLField(max_length=500, null=True)),
                ('project_link', models.URLField(max_length=500, null=True)),
                ('project_photo', models.ImageField(blank=True, null=True, upload_to='project_photos/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(default='New profile', max_length=50)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('about', models.TextField(max_length=500)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/%d/')),
                ('github_link', models.URLField(max_length=250, null=True)),
                ('twitter_link', models.URLField(max_length=250, null=True)),
                ('linkedin_link', models.URLField(max_length=250, null=True)),
                ('educations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foliomine.education')),
                ('experiences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foliomine.experience')),
                ('projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foliomine.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
