# Generated by Django 4.1.4 on 2022-12-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('about', models.TextField(max_length=500)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/%d/')),
                ('github_link', models.URLField(max_length=250, null=True)),
                ('twitter_link', models.URLField(max_length=250, null=True)),
                ('linkedin_link', models.URLField(max_length=250, null=True)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('hashed_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_details', models.TextField(max_length=2000)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foliomine.profile')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foliomine.user'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_profile', models.TextField(max_length=50)),
                ('company_name', models.TextField(max_length=50)),
                ('details', models.TextField(max_length=2000)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foliomine.profile')),
            ],
            options={
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField()),
                ('degree', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=5, null=True)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foliomine.profile')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
    ]
