# Generated by Django 4.1.4 on 2023-06-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foliomine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.AddField(
            model_name='education',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foliomine.profile'),
        ),
        migrations.AddField(
            model_name='experience',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foliomine.profile'),
        ),
        migrations.AddField(
            model_name='project',
            name='profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foliomine.profile'),
        ),
    ]
