# Generated by Django 4.1.4 on 2023-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foliomine', '0002_alter_profile_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(default='New profile', max_length=50),
        ),
    ]
